name: Verademo Scanning Example Github

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test]

jobs:
  Scans:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  
      - name: Build with Maven
        run: mvn -f app/pom.xml clean package 

      - name: Get the Java API wrapper
        uses: wei/curl@master
        with:
          args: -sS -o VeracodeJavaAPI.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.6.5.8/vosp-api-wrappers-java-19.6.5.8.jar"

      - name: Start SAST scan
        run: java -jar VeracodeJavaAPI.jar -action uploadandscan -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" -appname Github-import-issues-2-scan -createprofile true -version "GitHub Actions job $GITHUB_RUN_NUMBER" -filepath ./app/target/verademo.war --file verademo.war -jo results.json -jf results.json -fjf filtered_results.json 
        continue-on-error: true
      - name: save standard results
        uses: actions/upload-artifact@v1
        with:
          name: ScanResults
          path: results.json
      - name: save filtered results
        uses: actions/upload-artifact@v1
        with:
          name: filtered-results
          path: filtered_results.json
        
  import_flaws_job:
      runs-on: ubuntu-latest
      needs: Scans
      name: import flaws

      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get flaw file
        uses: actions/download-artifact@v2
        with:
          name: filtered-results

      - name: Flaw importer action step
        id: import
        uses: ./
        with:
          scan-results-json: 'filtered_results.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
#          source-base-path_1: "com/veracode:src/main/java/com/veracode" 
#          source-base-path_2: "WEB-INF:src/main/webapp/WEB-INF"
#          commit-hash: ${{ GITHUB.SHA }}
